language: node_js
node_js:
  - 18

# Define the stages
stages:
  - test

jobs:
  include:
    - stage: test
      name: "Test Server"
      before_script:
        - cd server
      script:
        - npm install
        - npm run start-server & # Start the server in the background
        - sleep 10 # Wait for the server to start (adjust this time as needed)
        - npm run check-db # Use your check-db script to verify server and database connection

    - stage: test
      name: "Test Client"
      before_script:
        - cd client
      script:
        - npm install
        - npm run dev & # Start the Vite server in the background
        - sleep 10 # Wait for the Vite server to start (adjust this time as needed)
        - npm run check-client # Use your script to verify the client
