language: node_js
node_js:
  - "16"

cache:
  directories:
    - client/node_modules

before_install:
  - cd client

install:
  - npm install

# In the script section, start the server and use a flag to indicate success
script:
  - npm run start &  # Start the server in the background
  - sleep 5  # Wait for the server to start (adjust as needed)
  - (curl -sS http://localhost:3000 || true) | grep "Compiled successfully"  # Check if the server output contains the success message
